### ISSUE TITLE
প্রাইভেট -> গোপনীয়

### ISSUE THREAD

**Issue by khalid32** [mozillabd/l10n#16]
[comment]: To know about your Firefox version and build date go to settings-> Mozilla Aurora-> About Aurora. [or type 'about:support' in address bar]
- **Product Name**: Firefox for Android
- **Version**: 51.0a2
- **Build Date**: 02-10-2016
- **Bug Description**: Translation Consistency
- **Actual Behavior (Error)**: প্রাইভেট
- **Steps to Reproduce**:
                   1.open 'Firefox for Android'
               2. Go to 'ইতিহাস'
- **Expected Behavior**: গোপনীয়
- **Screen shot(if any)**: 
  ![screenshot_2016-10-02-16-43-57 v01](https://cloud.githubusercontent.com/assets/8571179/19020103/aeb8bc00-88c0-11e6-9efe-78abc6edade8.png)

**Comment by bellayet** [comment]
Replaced with ব্যাক্তিগত at Pootle.
