### ISSUE TITLE
Aurora হোম -> Aurora নীড়

### ISSUE THREAD

**Issue by khalid32** [mozillabd/l10n#17]
[comment]: To know about your Firefox version and build date go to settings-> Mozilla Aurora-> About Aurora. [or type 'about:support' in address bar]
- **Product Name**: Firefox for Android
- **Version**: 51.0a2
- **Build Date**: 02-10-2016
- **Bug Description**: Translation Consistency
- **Actual Behavior (Error)**: Aurora হোম
- **Steps to Reproduce**:
      1. open Firefox for Android
      2. Go to 'New Tab'
- **Expected Behavior**: Aurora নীড়
- **Screen shot(if any)**:
  ![screenshot_2016-10-02-17-07-54 v01](https://cloud.githubusercontent.com/assets/8571179/19020221/7e9d5e96-88c4-11e6-8919-b97ab3819152.png)

**Comment by bellayet** [comment]
Fixed at Pootle.
