### ISSUE TITLE
হালনাগাদ করতে পরীক্ষা করুন -> হালনাগাদ করতে যাচাই করুন

### ISSUE THREAD

**Issue by khalid32** [mozillabd/l10n#18]
[comment]: To know about your Firefox version and build date go to settings-> Mozilla Aurora-> About Aurora. [or type 'about:support' in address bar]
- **Product Name**: Firefox for Android
- **Version**: 51.0a2
- **Build Date**: 02-10-2016
- **Bug Description**: Translation Consistency
- **Actual Behavior (Error)**: হালনাগাদ করতে পরীক্ষা করুন
- **Steps to Reproduce**: 
      1.open Firefox for Android
  1. Go to 'Open menu' >> সেটিং >> Mozilla Aurora >> Aurora সম্পর্কে
- **Expected Behavior**: হালনাগাদ করতে যাচাই করুন
- **Screen shot(if any)**:
  ![screenshot_2016-10-02-17-26-56 v01](https://cloud.githubusercontent.com/assets/8571179/19020292/b17a2b08-88c6-11e6-93a9-5b54d4c869f9.png)

**Comment by bellayet** [comment]
Fixed at Pootle.
