### ISSUE TITLE
ভৈগোলিক -> ভৌগলিক

### ISSUE THREAD

**Issue by smsnobin77** [mozillabd/l10n#23]
[comment]: To know about your Firefox version and build date go to সেটিং -> গোপনীয়তা -> Mozilla লোকেশন সার্ভিস.
- **Product Name**: Firefox for Android
- **Version**: 51.0a2
- **Build Date**: 02-10-2016
- **Bug Description**: Translation Consistency
- **Actual Behavior (Error)**: ভৈগোলিক 
- **Steps to Reproduce**:  সেটিং -> গোপনীয়তা -> Mozilla লোকেশন সার্ভিস
- **Expected Behavior**: ভৌগলিক
- **Screen shot(if any)**: 
  ![screenshot_2016-10-03-11-26-47](https://cloud.githubusercontent.com/assets/12386703/19046478/62a146de-89bf-11e6-8333-15ad5eff6abd.jpg)

**Comment by bellayet** [comment]
Fixed at Pootle.
