### ISSUE TITLE
ব্রাউসার -> ব্রাউজার

### ISSUE THREAD

**Issue by smsnobin77** [mozillabd/l10n#24]
[comment]: To know about your Firefox version and build date go to সেটিং -> গোপনীয়তা -> Aurora হেলথ রিপোর্ট.
- **Product Name**: Firefox for Android
- **Version**: 51.0a2
- **Build Date**: 02-10-2016
- **Bug Description**: Translation Consistency
- **Actual Behavior (Error)**: ব্রাউসার
- **Steps to Reproduce**:  সেটিং -> গোপনীয়তা -> Aurora হেলথ রিপোর্ট
- **Expected Behavior**: ব্রাউজার
- **Screen shot(if any)**: 
  ![screenshot_2016-10-03-11-26-47](https://cloud.githubusercontent.com/assets/12386703/19046649/2ad20846-89c0-11e6-8cef-3317820e1c33.jpg)

**Comment by bellayet** [comment]
Fixed at Pootle.
