### ISSUE TITLE
অ্যাড-অন -> অ্যাড-অন্স

### ISSUE THREAD

**Issue by khalid32** [mozillabd/l10n#28]
[comment]: To know about your Firefox version and build date go to settings-> Mozilla Aurora-> About Aurora. [or type 'about:support' in address bar]
- **Product Name**: Firefox for Android
- **Version**: 51.0a2
- **Build Date**: 06-10-2016
- **Bug Description**: Translation Consistency
- **Actual Behavior (Error)**: অ্যাড-অন
- **Steps to Reproduce**: 
              1.open Firefox for Android 
              2. Go to 'Open Menu' >> টুল
- **Expected Behavior**: অ্যাড-অন্স
- **Screen shot(if any)**: 
  ![screenshot_2016-10-07-00-52-39 v01](https://cloud.githubusercontent.com/assets/8571179/19166898/4f35983e-8c2b-11e6-8e2b-c395b2b35212.png)

**Comment by bellayet** [comment]
এতা অ্যাড-অন হবে। কারন স যুক্ত করলে তা ইংরেজি বহুবচন হবে যা বাংলায় কোন অর্থ বহন করে না।
