### ISSUE TITLE
আপারনার -> আপনার

### ISSUE THREAD

**Issue by khalid32** [mozillabd/l10n#6]
- **Product Name**: Firefox for Android
- **Version**: 51.0a2
- **Build Date**: 29-09-2016
- **Bug Description**:
- **Actual Behavior (Error)**: আমরা কোন ইতিহাস মনে রাখব না, কিন্তু ডাউনলোড করা ফাইল এবং নতুন বুকমার্ক গুলি আপারনার ডিভাইস এ সংরক্ষিত থাকবে।
- **Steps to Reproduce**: নতুন ট্যাব -> একান্ত ব্রাউজিং
- **Expected Behavior**: আমরা কোন ইতিহাস মনে রাখব না, কিন্তু ডাউনলোড করা ফাইল এবং নতুন বুকমার্ক গুলি আপনার ডিভাইস এ সংরক্ষিত থাকবে।
- **Screenshot(if any)**:
  ![private](https://cloud.githubusercontent.com/assets/8571179/18966502/3b8eaf6a-86a3-11e6-8622-ea68be198140.png)

**Comment by bellayet** [comment]
Fixed at Pootle.
